### ISSUE TITLE
GetAll causes runtime exception

### ISSUE THREAD

**Issue by vedatappsamurai** [ip2location/ip2proxy-go#1]
Hi,

We recently upgraded our ip2proxy package version from `2.2.0` to `2.3.0`, and we started to get the following exception on calling `db.GetAll("8.8.8.8")`:
```
panic: runtime error: slice bounds out of range [:16] with capacity 12

goroutine 1 [running]:
github.com/ip2location/ip2proxy-go.(*DB).readuint32_row(0xc0001ce070, 0xc00049af10, 0xc, 0xc, 0xc, 0x0)
	/Users/USER/go/pkg/mod/github.com/ip2location/ip2proxy-go@v2.3.0+incompatible/ip2proxy.go:195 +0xbf
github.com/ip2location/ip2proxy-go.(*DB).query(0xc0001ce070, 0x177e7ea, 0x7, 0xc000000fff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/USER/go/pkg/mod/github.com/ip2location/ip2proxy-go@v2.3.0+incompatible/ip2proxy.go:874 +0x10f6
github.com/ip2location/ip2proxy-go.(*DB).GetAll(0xc0001ce070, 0x177e7ea, 0x7, 0x0, 0x0, 0x0)
	/Users/USER/go/pkg/mod/github.com/ip2location/ip2proxy-go@v2.3.0+incompatible/ip2proxy.go:636 +0xb5
...
```

After trying to debug it, I've found out that the exception is caused at:
https://github.com/ip2location/ip2proxy-go/blob/5f6cbea4cf350ee98cac3871c5d6b4bd13f7a09c/ip2proxy.go#L871-L877
`row` is 12 bytes and `d.readuint32_row` tries to read range `[12:16]`.

We need this fixed to use release `v2.3.0` to benefit from concurrency improvements.

**Comment by vedatappsamurai** [comment]
I made a mistake of using ip2location DB in the ip2proxy client. Using the DB for ip2proxy fixed the issue.
